-- create terraform role
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE TERRAFORM_SR COMMENT = 'For terraform role';

-- GRANT ROLE ACCOUNTADMIN TO ROLE TERRAFORM_SR;
-- REVOKE ROLE ACCOUNTADMIN FROM ROLE TERRAFORM_SR;
GRANT ROLE SECURITYADMIN TO ROLE TERRAFORM_SR;
GRANT ROLE SYSADMIN TO ROLE TERRAFORM_SR;

--GRANT MODIFY ON RESOURCE MONITOR MONITOR_TERRAFORM TO ROLE TERRAFORM_SR;

-- Assigning created roles to specific users
-- Terraformを実行するユーザーにロールを付与
GRANT ROLE TERRAFORM_SR TO USER {NAME};

-- create FR_SECURITY_MANAGER role
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE FR_SECURITY_MANAGER COMMENT = 'For security manager role';

GRANT ROLE SECURITYADMIN TO ROLE FR_SECURITY_MANAGER;
GRANT ROLE FR_SECURITY_MANAGER TO USER {NAME};
