USE ROLE SYSADMIN;

-- create terraform user
CREATE OR REPLACE WAREHOUSE TERRAFORM_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_TIMEOUT_IN_SECONDS = 600 --10min
    COMMENT = 'For terraform warehouse';

-- create user
USE ROLE USERADMIN;
CREATE OR REPLACE USER TERRAFORM_USER
    RSA_PUBLIC_KEY = '{RSA key}' -- set public key
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'For terraform user';

-- create terraform role
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE TERRAFORM COMMENT = 'For terraform role';

-- ACCOUNTADMINロールの付与は推奨されていない。
--GRANT ROLE ACCOUNTADMIN TO ROLE TERRAFORM;
GRANT ROLE SECURITYADMIN TO ROLE TERRAFORM;
GRANT ROLE SYSADMIN TO ROLE TERRAFORM;

GRANT MODIFY ON RESOURCE MONITOR MONITOR_TERRAFORM TO ROLE TERRAFORM;

-- Assigning created roles to specific users
GRANT ROLE TERRAFORM TO USER TERRAFORM_USER;