USE ROLE SYSADMIN;

-- create terraform user
CREATE OR REPLACE WAREHOUSE TERRAFORM_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    MAX_CLUSTER_COUNT = 1
    MIN_CLUSTER_COUNT = 1
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_TIMEOUT_IN_SECONDS = 600 --10min
    COMMENT = 'For terraform warehouse';

-- create user
USE ROLE USERADMIN;
CREATE OR REPLACE USER TERRAFORM_USER
    TYPE = SERVICE
    RSA_PUBLIC_KEY = '{RSA key}' -- set public key
    COMMENT = 'For terraform user';

-- create terraform role
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE TERRAFORM_SR COMMENT = 'For terraform role';

GRANT ROLE ACCOUNTADMIN TO ROLE TERRAFORM_SR;
GRANT ROLE SECURITYADMIN TO ROLE TERRAFORM_SR;
GRANT ROLE SYSADMIN TO ROLE TERRAFORM_SR;

--GRANT MODIFY ON RESOURCE MONITOR MONITOR_TERRAFORM TO ROLE TERRAFORM_SR;

-- Assigning created roles to specific users
--GRANT ROLE TERRAFORM_SR TO USER TERRAFORM_USER;

GRANT ROLE TERRAFORM_SR TO USER THINKER_HUANG;