USE ROLE FR_SECURITY_MANAGER;
USE DATABASE SECURITY;
USE SCHEMA AUTHENTICATION;

-- アカウント全体の認証ポリシーを設定します。
-- https://docs.snowflake.com/en/user-guide/authentication-policies#label-authentication-policy-hardening-authentication
CREATE AUTHENTICATION POLICY REQUIRE_MFA_AUTHENTICATION_ACCOUNT_POLICY
  AUTHENTICATION_METHODS = ('PASSWORD')
  CLIENT_TYPES = ('SNOWFLAKE_UI')
  MFA_AUTHENTICATION_METHODS = ('PASSWORD')
  MFA_ENROLLMENT = REQUIRED;

ALTER ACCOUNT SET AUTHENTICATION POLICY REQUIRE_MFA_AUTHENTICATION_ACCOUNT_POLICY;

/*
SELECT *
FROM TABLE(
    SECURITY.INFORMATION_SCHEMA.POLICY_REFERENCES(
      POLICY_NAME => 'SECURITY.AUTHENTICATION.REQUIRE_MFA_AUTHENTICATION_ACCOUNT_POLICY'
  )
);
*/

-- 開発者用の認証ポリシーを設定します。
CREATE AUTHENTICATION POLICY developer_authentication_user_policy
  AUTHENTICATION_METHODS = ('ALL')
  CLIENT_TYPES = ('ALL')
  MFA_AUTHENTICATION_METHODS = ('PASSWORD')
  MFA_ENROLLMENT = REQUIRED;

ALTER USER RYOTA_HASEGAWA SET AUTHENTICATION POLICY developer_authentication_user_policy;
ALTER USER HUNAG SET AUTHENTICATION POLICY developer_authentication_user_policy;

/*
SELECT *
FROM TABLE(
    SECURITY.INFORMATION_SCHEMA.POLICY_REFERENCES(
      POLICY_NAME => 'SECURITY.AUTHENTICATION.developer_authentication_user_policy'
  )
);
*/

-- オプションのMFA認証ポリシーを設定します。
CREATE AUTHENTICATION POLICY optional_mfa_authentication_user_policy
  AUTHENTICATION_METHODS = ('PASSWORD')
  CLIENT_TYPES = ('SNOWFLAKE_UI')
  MFA_AUTHENTICATION_METHODS = ('PASSWORD')
  MFA_ENROLLMENT = OPTIONAL;

ALTER USER {USER_NAME} SET AUTHENTICATION POLICY optional_mfa_authentication_user_policy;

/*
SELECT *
FROM TABLE(
    SECURITY.INFORMATION_SCHEMA.POLICY_REFERENCES(
      POLICY_NAME => 'SECURITY.AUTHENTICATION.optional_mfa_authentication_user_policy'
  )
);
*/


-- パスワードポリシーを確認します。
/*
SELECT *
FROM TABLE(
    SECURITY.INFORMATION_SCHEMA.POLICY_REFERENCES(
      POLICY_NAME => 'SECURITY.AUTHENTICATION.PASSWORD_POLICY_DEFAULT'
  )
);
*/