USE ROLE ACCOUNTADMIN;

-- ACCOUNT MONITOR
create RESOURCE MONITOR 
    IDENTIFIER('"SNOWFLAKE_ACCOUNT_MONITOR"') 
        NOTIFY_USERS = ('RYOTA_HASEGAWA')
        CREDIT_QUOTA = 100 
        FREQUENCY = 'MONTHLY' 
        START_TIMESTAMP = 'IMMEDIATELY' 
        TRIGGERS ON 90 PERCENT 
            DO SUSPEND ON 100 PERCENT 
            DO SUSPEND_IMMEDIATE ON 110 PERCENT 
            DO NOTIFY ON 80 PERCENT 
            DO NOTIFY ON 70 PERCENT 
            DO NOTIFY ON 50 PERCENT 
            DO NOTIFY ON 30 PERCENT 
            DO NOTIFY;

alter ACCOUNT set RESOURCE_MONITOR = 'SNOWFLAKE_ACCOUNT_MONITOR';


create RESOURCE 
    MONITOR IDENTIFIER('"WAREHOUSES_STANDARD_MONITOR"') 
    NOTIFY_USERS = ('RYOTA_HASEGAWA')
    CREDIT_QUOTA = 100 
    FREQUENCY = 'MONTHLY' 
    START_TIMESTAMP = 'IMMEDIATELY' 
    TRIGGERS ON 90 PERCENT 
        DO SUSPEND ON 100 PERCENT 
        DO SUSPEND_IMMEDIATE ON 110 PERCENT 
        DO NOTIFY ON 80 PERCENT 
        DO NOTIFY ON 70 PERCENT 
        DO NOTIFY ON 50 PERCENT 
        DO NOTIFY ON 30 PERCENT 
        DO NOTIFY;

alter WAREHOUSE IDENTIFIER('"TERRAFORM_WH"') set RESOURCE_MONITOR = 'WAREHOUSES_STANDARD_MONITOR';
alter WAREHOUSE IDENTIFIER('"DATA_ENGINEER_WH"') set RESOURCE_MONITOR = 'WAREHOUSES_STANDARD_MONITOR';
alter WAREHOUSE IDENTIFIER('"DATA_ANALYST_WH"') set RESOURCE_MONITOR = 'WAREHOUSES_STANDARD_MONITOR';
alter WAREHOUSE IDENTIFIER('"DATA_READER_WH"') set RESOURCE_MONITOR = 'WAREHOUSES_STANDARD_MONITOR';
alter WAREHOUSE IDENTIFIER('"ETL_SERVICE_WH"') set RESOURCE_MONITOR = 'WAREHOUSES_STANDARD_MONITOR';

SHOW RESOURCE MONITORS;